//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class backupmediafamily
    {
        public int media_set_id { get; set; }
        public byte family_sequence_number { get; set; }
        public Nullable<System.Guid> media_family_id { get; set; }
        public Nullable<int> media_count { get; set; }
        public string logical_device_name { get; set; }
        public string physical_device_name { get; set; }
        public Nullable<byte> device_type { get; set; }
        public Nullable<int> physical_block_size { get; set; }
        public byte mirror { get; set; }
    
        public virtual backupmediaset backupmediaset { get; set; }
    }
}
