//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_monitor_error_detail
    {
        public System.Guid agent_id { get; set; }
        public byte agent_type { get; set; }
        public int session_id { get; set; }
        public string database_name { get; set; }
        public int sequence_number { get; set; }
        public System.DateTime log_time { get; set; }
        public System.DateTime log_time_utc { get; set; }
        public string message { get; set; }
        public string source { get; set; }
        public string help_url { get; set; }
    }
}
