//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_secondaries
    {
        public Nullable<int> primary_id { get; set; }
        public string secondary_server_name { get; set; }
        public string secondary_database_name { get; set; }
        public string last_copied_filename { get; set; }
        public string last_loaded_filename { get; set; }
        public Nullable<System.DateTime> last_copied_last_updated { get; set; }
        public Nullable<System.DateTime> last_loaded_last_updated { get; set; }
        public Nullable<System.Guid> secondary_plan_id { get; set; }
        public Nullable<bool> copy_enabled { get; set; }
        public Nullable<bool> load_enabled { get; set; }
        public Nullable<int> out_of_sync_threshold { get; set; }
        public Nullable<int> threshold_alert { get; set; }
        public Nullable<bool> threshold_alert_enabled { get; set; }
        public Nullable<int> planned_outage_start_time { get; set; }
        public Nullable<int> planned_outage_end_time { get; set; }
        public Nullable<int> planned_outage_weekday_mask { get; set; }
        public Nullable<bool> allow_role_change { get; set; }
    
        public virtual log_shipping_primaries log_shipping_primaries { get; set; }
    }
}
