//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class msdb_version
    {
        public int id { get; set; }
        public string version_string { get; set; }
        public int version_major { get; set; }
        public int version_minor { get; set; }
        public int version_build { get; set; }
        public int version_revision { get; set; }
    }
}
