//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSdbms_datatype_mapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSdbms_datatype_mapping()
        {
            this.MSdbms_map1 = new HashSet<MSdbms_map>();
        }
    
        public int datatype_mapping_id { get; set; }
        public int map_id { get; set; }
        public int dest_datatype_id { get; set; }
        public Nullable<long> dest_precision { get; set; }
        public Nullable<int> dest_scale { get; set; }
        public Nullable<long> dest_length { get; set; }
        public Nullable<bool> dest_nullable { get; set; }
        public Nullable<int> dest_createparams { get; set; }
        public bool dataloss { get; set; }
    
        public virtual MSdbms_datatype MSdbms_datatype { get; set; }
        public virtual MSdbms_map MSdbms_map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSdbms_map> MSdbms_map1 { get; set; }
    }
}
