//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSdbms_map
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSdbms_map()
        {
            this.MSdbms_datatype_mapping = new HashSet<MSdbms_datatype_mapping>();
        }
    
        public int map_id { get; set; }
        public int src_dbms_id { get; set; }
        public int dest_dbms_id { get; set; }
        public int src_datatype_id { get; set; }
        public Nullable<long> src_len_min { get; set; }
        public Nullable<long> src_len_max { get; set; }
        public Nullable<long> src_prec_min { get; set; }
        public Nullable<long> src_prec_max { get; set; }
        public Nullable<long> src_scale_min { get; set; }
        public Nullable<long> src_scale_max { get; set; }
        public Nullable<bool> src_nullable { get; set; }
        public Nullable<int> default_datatype_mapping_id { get; set; }
    
        public virtual MSdbm MSdbm { get; set; }
        public virtual MSdbm MSdbm1 { get; set; }
        public virtual MSdbms_datatype MSdbms_datatype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSdbms_datatype_mapping> MSdbms_datatype_mapping { get; set; }
        public virtual MSdbms_datatype_mapping MSdbms_datatype_mapping1 { get; set; }
    }
}
