//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class restorefilegroup
    {
        public int restore_history_id { get; set; }
        public string filegroup_name { get; set; }
    
        public virtual restorehistory restorehistory { get; set; }
    }
}
