//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class syscollector_execution_log_internal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public syscollector_execution_log_internal()
        {
            this.syscollector_execution_stats_internal = new HashSet<syscollector_execution_stats_internal>();
        }
    
        public long log_id { get; set; }
        public Nullable<long> parent_log_id { get; set; }
        public int collection_set_id { get; set; }
        public Nullable<int> collection_item_id { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> last_iteration_time { get; set; }
        public Nullable<System.DateTime> finish_time { get; set; }
        public Nullable<short> runtime_execution_mode { get; set; }
        public short status { get; set; }
        public string @operator { get; set; }
        public Nullable<System.Guid> package_id { get; set; }
        public Nullable<System.Guid> package_execution_id { get; set; }
        public string failure_message { get; set; }
    
        public virtual syscollector_collection_sets_internal syscollector_collection_sets_internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syscollector_execution_stats_internal> syscollector_execution_stats_internal { get; set; }
    }
}
