//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class syscollector_collection_sets_internal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public syscollector_collection_sets_internal()
        {
            this.syscollector_collection_items_internal = new HashSet<syscollector_collection_items_internal>();
            this.syscollector_execution_log_internal = new HashSet<syscollector_execution_log_internal>();
        }
    
        public int collection_set_id { get; set; }
        public System.Guid collection_set_uid { get; set; }
        public Nullable<System.Guid> schedule_uid { get; set; }
        public string name { get; set; }
        public Nullable<int> name_id { get; set; }
        public string target { get; set; }
        public bool is_running { get; set; }
        public Nullable<int> proxy_id { get; set; }
        public bool is_system { get; set; }
        public Nullable<System.Guid> collection_job_id { get; set; }
        public Nullable<System.Guid> upload_job_id { get; set; }
        public short collection_mode { get; set; }
        public short logging_level { get; set; }
        public string description { get; set; }
        public Nullable<int> description_id { get; set; }
        public short days_until_expiration { get; set; }
        public bool dump_on_any_error { get; set; }
        public string dump_on_codes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syscollector_collection_items_internal> syscollector_collection_items_internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syscollector_execution_log_internal> syscollector_execution_log_internal { get; set; }
    }
}
