//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmaintplan_log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysmaintplan_log()
        {
            this.sysmaintplan_logdetail = new HashSet<sysmaintplan_logdetail>();
        }
    
        public System.Guid task_detail_id { get; set; }
        public Nullable<System.Guid> plan_id { get; set; }
        public Nullable<System.Guid> subplan_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<bool> succeeded { get; set; }
        public bool logged_remotely { get; set; }
        public string source_server_name { get; set; }
        public string plan_name { get; set; }
        public string subplan_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysmaintplan_logdetail> sysmaintplan_logdetail { get; set; }
        public virtual sysmaintplan_subplans sysmaintplan_subplans { get; set; }
    }
}
