//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class syspolicy_conditions_internal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public syspolicy_conditions_internal()
        {
            this.syspolicy_target_set_levels_internal = new HashSet<syspolicy_target_set_levels_internal>();
            this.syspolicy_policies_internal = new HashSet<syspolicy_policies_internal>();
            this.syspolicy_policies_internal1 = new HashSet<syspolicy_policies_internal>();
        }
    
        public int condition_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string description { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> facet_id { get; set; }
        public string expression { get; set; }
        public Nullable<short> is_name_condition { get; set; }
        public string obj_name { get; set; }
        public bool is_system { get; set; }
    
        public virtual syspolicy_management_facets syspolicy_management_facets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syspolicy_target_set_levels_internal> syspolicy_target_set_levels_internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syspolicy_policies_internal> syspolicy_policies_internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syspolicy_policies_internal> syspolicy_policies_internal1 { get; set; }
    }
}
