//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class syspolicy_policy_categories_internal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public syspolicy_policy_categories_internal()
        {
            this.syspolicy_policies_internal = new HashSet<syspolicy_policies_internal>();
            this.syspolicy_policy_category_subscriptions_internal = new HashSet<syspolicy_policy_category_subscriptions_internal>();
        }
    
        public int dbpolicy_category_id { get; set; }
        public string name { get; set; }
        public bool mandate_database_subscriptions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syspolicy_policies_internal> syspolicy_policies_internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syspolicy_policy_category_subscriptions_internal> syspolicy_policy_category_subscriptions_internal { get; set; }
    }
}
