//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class syspolicy_system_health_state_internal
    {
        public long health_state_id { get; set; }
        public int policy_id { get; set; }
        public System.DateTime last_run_date { get; set; }
        public string target_query_expression_with_id { get; set; }
        public string target_query_expression { get; set; }
        public bool result { get; set; }
    
        public virtual syspolicy_policies_internal syspolicy_policies_internal { get; set; }
    }
}
