//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class syspolicy_facet_events
    {
        public int management_facet_id { get; set; }
        public string event_name { get; set; }
        public string target_type { get; set; }
        public string target_type_alias { get; set; }
    
        public virtual syspolicy_management_facets syspolicy_management_facets { get; set; }
    }
}
