//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssubsystem
    {
        public int subsystem_id { get; set; }
        public string subsystem { get; set; }
        public Nullable<int> description_id { get; set; }
        public string subsystem_dll { get; set; }
        public string agent_exe { get; set; }
        public string start_entry_point { get; set; }
        public string event_entry_point { get; set; }
        public string stop_entry_point { get; set; }
        public Nullable<int> max_worker_threads { get; set; }
    }
}
