//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_volumes_stub
    {
        public int ID { get; set; }
        public string virtual_server_name { get; set; }
        public string physical_server_name { get; set; }
        public string volume_device_id { get; set; }
        public string volume_name { get; set; }
        public Nullable<float> total_space_available { get; set; }
        public Nullable<float> free_space { get; set; }
        public Nullable<float> total_space_utilized { get; set; }
        public Nullable<float> percent_total_space_utilization { get; set; }
        public Nullable<System.DateTimeOffset> processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
        public string powershell_path { get; set; }
    }
}
