//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_mi_smo_objects_to_collect_internal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysutility_mi_smo_objects_to_collect_internal()
        {
            this.sysutility_mi_smo_properties_to_collect_internal = new HashSet<sysutility_mi_smo_properties_to_collect_internal>();
        }
    
        public int object_type { get; set; }
        public string sfc_query { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sysutility_mi_smo_properties_to_collect_internal> sysutility_mi_smo_properties_to_collect_internal { get; set; }
    }
}
