//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_mi_smo_stage_internal
    {
        public int object_type { get; set; }
        public string urn { get; set; }
        public string property_name { get; set; }
        public string server_instance_name { get; set; }
        public string physical_server_name { get; set; }
    }
}
