//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_policy_violations_internal
    {
        public int health_policy_id { get; set; }
        public int policy_id { get; set; }
        public string policy_name { get; set; }
        public int history_id { get; set; }
        public int detail_id { get; set; }
        public string target_query_expression { get; set; }
        public string target_query_expression_with_id { get; set; }
        public Nullable<System.DateTime> execution_date { get; set; }
        public Nullable<int> result { get; set; }
    }
}
