//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_aggregated_mi_health_internal
    {
        public int mi_count { get; set; }
        public int mi_healthy_count { get; set; }
        public int mi_unhealthy_count { get; set; }
        public int mi_over_utilize_count { get; set; }
        public int mi_under_utilize_count { get; set; }
        public int mi_on_over_utilized_computer_count { get; set; }
        public int mi_on_under_utilized_computer_count { get; set; }
        public int mi_with_files_on_over_utilized_volume_count { get; set; }
        public int mi_with_files_on_under_utilized_volume_count { get; set; }
        public int mi_with_over_utilized_file_count { get; set; }
        public int mi_with_under_utilized_file_count { get; set; }
        public int mi_with_over_utilized_processor_count { get; set; }
        public int mi_with_under_utilized_processor_count { get; set; }
        public int set_number { get; set; }
    }
}
