//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_datafiles_stub
    {
        public string urn { get; set; }
        public string powershell_path { get; set; }
        public Nullable<System.DateTimeOffset> processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
        public string server_instance_name { get; set; }
        public string database_name { get; set; }
        public string filegroup_name { get; set; }
        public string parent_urn { get; set; }
        public string physical_server_name { get; set; }
        public string volume_name { get; set; }
        public string volume_device_id { get; set; }
        public Nullable<float> Growth { get; set; }
        public Nullable<short> GrowthType { get; set; }
        public Nullable<float> MaxSize { get; set; }
        public string Name { get; set; }
        public Nullable<float> Size { get; set; }
        public Nullable<float> UsedSpace { get; set; }
        public string FileName { get; set; }
        public Nullable<long> VolumeFreeSpace { get; set; }
        public Nullable<float> available_space { get; set; }
    }
}
