//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_mi_session_statistics_internal
    {
        public System.DateTimeOffset collection_time { get; set; }
        public int session_id { get; set; }
        public string dac_instance_name { get; set; }
        public string database_name { get; set; }
        public System.DateTime login_time { get; set; }
        public int cumulative_cpu_ms { get; set; }
    }
}
