//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod07Demo01
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_policy_check_conditions_internal
    {
        public int target_type { get; set; }
        public int resource_type { get; set; }
        public int utilization_type { get; set; }
        public string facet_name { get; set; }
        public string attribute_name { get; set; }
        public int operator_type { get; set; }
        public string property_name { get; set; }
    }
}
