//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_primary_databases
    {
        public System.Guid primary_id { get; set; }
        public string primary_database { get; set; }
        public string backup_directory { get; set; }
        public string backup_share { get; set; }
        public int backup_retention_period { get; set; }
        public System.Guid backup_job_id { get; set; }
        public string monitor_server { get; set; }
        public Nullable<bool> user_specified_monitor { get; set; }
        public bool monitor_server_security_mode { get; set; }
        public string last_backup_file { get; set; }
        public Nullable<System.DateTime> last_backup_date { get; set; }
        public byte backup_compression { get; set; }
    }
}
