//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_secondary_databases
    {
        public string secondary_database { get; set; }
        public System.Guid secondary_id { get; set; }
        public int restore_delay { get; set; }
        public bool restore_all { get; set; }
        public bool restore_mode { get; set; }
        public bool disconnect_users { get; set; }
        public Nullable<int> block_size { get; set; }
        public Nullable<int> buffer_count { get; set; }
        public Nullable<int> max_transfer_size { get; set; }
        public string last_restored_file { get; set; }
        public Nullable<System.DateTime> last_restored_date { get; set; }
    }
}
