//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_primaries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public log_shipping_primaries()
        {
            this.log_shipping_secondaries = new HashSet<log_shipping_secondaries>();
        }
    
        public int primary_id { get; set; }
        public string primary_server_name { get; set; }
        public string primary_database_name { get; set; }
        public Nullable<System.Guid> maintenance_plan_id { get; set; }
        public int backup_threshold { get; set; }
        public int threshold_alert { get; set; }
        public bool threshold_alert_enabled { get; set; }
        public string last_backup_filename { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public int planned_outage_start_time { get; set; }
        public int planned_outage_end_time { get; set; }
        public int planned_outage_weekday_mask { get; set; }
        public string source_directory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log_shipping_secondaries> log_shipping_secondaries { get; set; }
    }
}
