//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_secondary
    {
        public System.Guid secondary_id { get; set; }
        public string primary_server { get; set; }
        public string primary_database { get; set; }
        public string backup_source_directory { get; set; }
        public string backup_destination_directory { get; set; }
        public int file_retention_period { get; set; }
        public System.Guid copy_job_id { get; set; }
        public System.Guid restore_job_id { get; set; }
        public string monitor_server { get; set; }
        public bool monitor_server_security_mode { get; set; }
        public Nullable<bool> user_specified_monitor { get; set; }
        public string last_copied_file { get; set; }
        public Nullable<System.DateTime> last_copied_date { get; set; }
    }
}
