//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_monitor_primary
    {
        public System.Guid primary_id { get; set; }
        public string primary_server { get; set; }
        public string primary_database { get; set; }
        public int backup_threshold { get; set; }
        public int threshold_alert { get; set; }
        public bool threshold_alert_enabled { get; set; }
        public string last_backup_file { get; set; }
        public Nullable<System.DateTime> last_backup_date { get; set; }
        public Nullable<System.DateTime> last_backup_date_utc { get; set; }
        public int history_retention_period { get; set; }
    }
}
