//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_shipping_primary_secondaries
    {
        public System.Guid primary_id { get; set; }
        public string secondary_server { get; set; }
        public string secondary_database { get; set; }
    }
}
