//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSdbms_datatype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSdbms_datatype()
        {
            this.MSdbms_datatype_mapping = new HashSet<MSdbms_datatype_mapping>();
            this.MSdbms_map = new HashSet<MSdbms_map>();
        }
    
        public int datatype_id { get; set; }
        public int dbms_id { get; set; }
        public string type { get; set; }
        public int createparams { get; set; }
    
        public virtual MSdbm MSdbm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSdbms_datatype_mapping> MSdbms_datatype_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSdbms_map> MSdbms_map { get; set; }
    }
}
