//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class restorefile
    {
        public int restore_history_id { get; set; }
        public Nullable<decimal> file_number { get; set; }
        public string destination_phys_drive { get; set; }
        public string destination_phys_name { get; set; }
    
        public virtual restorehistory restorehistory { get; set; }
    }
}
