//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class suspect_pages
    {
        public int database_id { get; set; }
        public int file_id { get; set; }
        public long page_id { get; set; }
        public int event_type { get; set; }
        public int error_count { get; set; }
        public System.DateTime last_update_date { get; set; }
    }
}
