//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class syscollector_execution_stats_internal
    {
        public long log_id { get; set; }
        public string task_name { get; set; }
        public Nullable<int> execution_row_count_in { get; set; }
        public Nullable<int> execution_row_count_out { get; set; }
        public Nullable<int> execution_row_count_errors { get; set; }
        public Nullable<int> execution_time_ms { get; set; }
        public System.DateTime log_time { get; set; }
    
        public virtual syscollector_execution_log_internal syscollector_execution_log_internal { get; set; }
    }
}
