//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class syscachedcredential
    {
        public string login_name { get; set; }
        public bool has_server_access { get; set; }
        public bool is_sysadmin_member { get; set; }
        public System.DateTime cachedate { get; set; }
    }
}
