//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmail_send_retries
    {
        public System.Guid conversation_handle { get; set; }
        public int mailitem_id { get; set; }
        public int send_attempts { get; set; }
        public System.DateTime last_send_attempt_date { get; set; }
    
        public virtual sysmail_mailitems sysmail_mailitems { get; set; }
    }
}
