//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmail_attachments
    {
        public int attachment_id { get; set; }
        public int mailitem_id { get; set; }
        public string filename { get; set; }
        public int filesize { get; set; }
        public byte[] attachment { get; set; }
        public System.DateTime last_mod_date { get; set; }
        public string last_mod_user { get; set; }
    
        public virtual sysmail_mailitems sysmail_mailitems { get; set; }
    }
}
