//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmail_principalprofile
    {
        public int profile_id { get; set; }
        public byte[] principal_sid { get; set; }
        public bool is_default { get; set; }
        public System.DateTime last_mod_datetime { get; set; }
        public string last_mod_user { get; set; }
    
        public virtual sysmail_profile sysmail_profile { get; set; }
    }
}
