//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class syspolicy_target_sets_internal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public syspolicy_target_sets_internal()
        {
            this.syspolicy_target_set_levels_internal = new HashSet<syspolicy_target_set_levels_internal>();
        }
    
        public int target_set_id { get; set; }
        public int object_set_id { get; set; }
        public string type_skeleton { get; set; }
        public string type { get; set; }
        public bool enabled { get; set; }
    
        public virtual syspolicy_object_sets_internal syspolicy_object_sets_internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syspolicy_target_set_levels_internal> syspolicy_target_set_levels_internal { get; set; }
    }
}
