//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class syspolicy_policy_category_subscriptions_internal
    {
        public int policy_category_subscription_id { get; set; }
        public string target_type { get; set; }
        public string target_object { get; set; }
        public int policy_category_id { get; set; }
    
        public virtual syspolicy_policy_categories_internal syspolicy_policy_categories_internal { get; set; }
    }
}
