//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysssispackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sysssispackage()
        {
            this.syscollector_collector_types_internal = new HashSet<syscollector_collector_types_internal>();
            this.syscollector_collector_types_internal1 = new HashSet<syscollector_collector_types_internal>();
        }
    
        public string name { get; set; }
        public System.Guid id { get; set; }
        public string description { get; set; }
        public System.DateTime createdate { get; set; }
        public System.Guid folderid { get; set; }
        public byte[] ownersid { get; set; }
        public byte[] packagedata { get; set; }
        public int packageformat { get; set; }
        public int packagetype { get; set; }
        public int vermajor { get; set; }
        public int verminor { get; set; }
        public int verbuild { get; set; }
        public string vercomments { get; set; }
        public System.Guid verid { get; set; }
        public bool isencrypted { get; set; }
        public byte[] readrolesid { get; set; }
        public byte[] writerolesid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syscollector_collector_types_internal> syscollector_collector_types_internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<syscollector_collector_types_internal> syscollector_collector_types_internal1 { get; set; }
    }
}
