//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysssispackagefolder
    {
        public System.Guid folderid { get; set; }
        public Nullable<System.Guid> parentfolderid { get; set; }
        public string foldername { get; set; }
    }
}
