//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_health_policies_internal
    {
        public int health_policy_id { get; set; }
        public string policy_name { get; set; }
        public string rollup_object_urn { get; set; }
        public int rollup_object_type { get; set; }
        public int target_type { get; set; }
        public int resource_type { get; set; }
        public int utilization_type { get; set; }
        public double utilization_threshold { get; set; }
        public Nullable<bool> is_global_policy { get; set; }
    }
}
