//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_databases_stub
    {
        public string urn { get; set; }
        public string powershell_path { get; set; }
        public Nullable<System.DateTimeOffset> processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
        public string server_instance_name { get; set; }
        public string parent_urn { get; set; }
        public string Collation { get; set; }
        public Nullable<short> CompatibilityLevel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> EncryptionEnabled { get; set; }
        public string Name { get; set; }
        public Nullable<short> RecoveryModel { get; set; }
        public Nullable<bool> Trustworthy { get; set; }
        public Nullable<byte> state { get; set; }
    }
}
