//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_filegroups_with_policy_violations_internal
    {
        public string server_instance_name { get; set; }
        public string database_name { get; set; }
        public string filegroup_name { get; set; }
        public int policy_id { get; set; }
        public int set_number { get; set; }
    }
}
