//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_dac_health_internal
    {
        public string dac_name { get; set; }
        public string dac_server_instance_name { get; set; }
        public int is_volume_space_over_utilized { get; set; }
        public int is_volume_space_under_utilized { get; set; }
        public int is_computer_processor_over_utilized { get; set; }
        public int is_computer_processor_under_utilized { get; set; }
        public int is_file_space_over_utilized { get; set; }
        public int is_file_space_under_utilized { get; set; }
        public int is_dac_processor_over_utilized { get; set; }
        public int is_dac_processor_under_utilized { get; set; }
        public bool is_policy_overridden { get; set; }
        public int set_number { get; set; }
        public System.DateTimeOffset processing_time { get; set; }
    }
}
