//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_cpu_utilization_stub
    {
        public Nullable<System.DateTimeOffset> processing_time { get; set; }
        public byte aggregation_type { get; set; }
        public byte object_type { get; set; }
        public string physical_server_name { get; set; }
        public string server_instance_name { get; set; }
        public string database_name { get; set; }
        public Nullable<float> percent_total_cpu_utilization { get; set; }
    }
}
