//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_mi_volumes_stage_internal
    {
        public string volume_device_id { get; set; }
        public string volume_name { get; set; }
        public decimal capacity_mb { get; set; }
        public decimal free_space_mb { get; set; }
        public string server_instance_name { get; set; }
        public string virtual_server_name { get; set; }
        public string physical_server_name { get; set; }
    }
}
