//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_mi_file_space_health_internal
    {
        public string server_instance_name { get; set; }
        public string database_name { get; set; }
        public string fg_name { get; set; }
        public int over_utilized_count { get; set; }
        public int under_utilized_count { get; set; }
        public int file_type { get; set; }
        public int set_number { get; set; }
        public System.DateTimeOffset processing_time { get; set; }
    }
}
