//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_processing_state_internal
    {
        public Nullable<System.DateTimeOffset> latest_processing_time { get; set; }
        public Nullable<int> latest_health_state_id { get; set; }
        public Nullable<int> next_health_state_id { get; set; }
        public int id { get; set; }
    }
}
