//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_mi_configuration_internal
    {
        public int configuration_id { get; set; }
        public string ucp_instance_name { get; set; }
        public string mdw_database_name { get; set; }
    }
}
