//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_managed_instances_internal
    {
        public int instance_id { get; set; }
        public string instance_name { get; set; }
        public string virtual_server_name { get; set; }
        public System.DateTimeOffset date_created { get; set; }
        public string created_by { get; set; }
        public string agent_proxy_account { get; set; }
        public string cache_directory { get; set; }
        public int management_state { get; set; }
    }
}
