//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_mi_dac_execution_statistics_internal
    {
        public string dac_instance_name { get; set; }
        public string database_name { get; set; }
        public int database_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTimeOffset> first_collection_time { get; set; }
        public Nullable<System.DateTimeOffset> last_collection_time { get; set; }
        public Nullable<System.DateTimeOffset> last_upload_time { get; set; }
        public Nullable<long> lifetime_cpu_time_ms { get; set; }
        public Nullable<long> cpu_time_ms_at_last_upload { get; set; }
    }
}
