//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod08Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_aggregated_dac_health_internal
    {
        public int dac_count { get; set; }
        public int dac_healthy_count { get; set; }
        public int dac_unhealthy_count { get; set; }
        public int dac_over_utilize_count { get; set; }
        public int dac_under_utilize_count { get; set; }
        public int dac_on_over_utilized_computer_count { get; set; }
        public int dac_on_under_utilized_computer_count { get; set; }
        public int dac_with_files_on_over_utilized_volume_count { get; set; }
        public int dac_with_files_on_under_utilized_volume_count { get; set; }
        public int dac_with_over_utilized_file_count { get; set; }
        public int dac_with_under_utilized_file_count { get; set; }
        public int dac_with_over_utilized_processor_count { get; set; }
        public int dac_with_under_utilized_processor_count { get; set; }
        public int set_number { get; set; }
    }
}
